### PR TITLE
convert nwb to pdf

### PR DESCRIPTION
**Pull request by ukos-git**
convert nwb to pdf.
Structuring is done in sweeps with cycle_id. Each sweep gets its own
page, each nwb file its pdf.

### CODE REVIEW

**Comment by ukos-git** [comment]
@t-b PR is to this fork.

**Comment by t-b** [comment]
@ukos-git Thanks. Work like a charm here.

I've added some quick hacks in https://github.com/t-b/ipfx/commit/37f34253f089473714cee77a9b84387510e8e466. Most changs should be self explaining. Regarding the PDF layout itself I would like to have always portrait, with the stimulus above the acquisition.

Some notes on the code:
- [ ] Make the code flake8 clean if not yet done
- [ ] Move the script to bin
- [ ] No code outside of functions/classes. The only exception being 

```
 if __name__ == "__main__":
    main()
```
- [ ] Please initialize dicts/lists with the shorthands `{}` and `[]`
- [ ] What are your rules for using `_` as a prefix/suffix for variable names? And for `__` as variable name prefix? These are really questions ;)
- [ ] add_annotation having `unit = None` makes for nicer code instead of using an empty string
- [ ] For reading the NWB file and creating the PDF you should use the the `with` statement from https://www.python.org/dev/peps/pep-0343/. This ensures that `close` is always called, even when an exception occurs. The pynwb example from [here](https://pynwb.readthedocs.io/en/latest/tutorials/domain/ecephys.html) also does that.
- [ ] Instead of _sweeps.ids() implement `__iter__` , see https://docs.python.org/3/library/stdtypes.html#typeiter, which allows to just write `for s in sweeps`.
- [ ] plot_sweepdata looks kind of unpythonic. Could you get rid of `i`? `enumerate` should help in deriving an index for the iteration if that is needed.

**Comment by ukos-git** [comment]
after adding your changes, python crashes with the following error:

```console
/home/matthias/Documents/Projects/python-xnwb-plotting/env/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
nwb:	/home/matthias/Documents/Projects/python-xnwb-plotting/data/nwb/2018_03_20_0001.nwb
pdf:	nwb.pdf

Traceback (most recent call last):
  File "ipfx/bin/nwb_to_pdf.py", line 288, in <module>
    sweeps = gather_sweeps(nwbfile)
  File "ipfx/bin/nwb_to_pdf.py", line 226, in gather_sweeps
    sweeps_.get(cycle_id).add_acquisition(key, acquisition)
  File "ipfx/bin/nwb_to_pdf.py", line 112, in add_acquisition
    self.__acquisition[key] = sweep_data(pcs)
  File "ipfx/bin/nwb_to_pdf.py", line 139, in __init__
    self._load_data(neurodata)
  File "ipfx/bin/nwb_to_pdf.py", line 148, in _load_data
    self.data['y'] = neurodata.data[()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/matthias/Documents/Projects/python-xnwb-plotting/env/local/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 412, in __getitem__
    if is_empty_dataspace(self.id):
  File "/home/matthias/Documents/Projects/python-xnwb-plotting/env/local/lib/python3.6/site-packages/h5py/_hl/base.py", line 82, in is_empty_dataspace
    if obj.get_space().get_simple_extent_type() == h5s.NULL:
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 288, in h5py.h5d.DatasetID.get_space
ValueError: Not a dataset (not a dataset)
```

I also skipped this request, as I don't know how to do something like this here

> [ ] plot_sweepdata looks kind of unpythonic. Could you get rid of i? enumerate should help in deriving an index for the iteration if that is needed.

**Comment by ukos-git** [comment]
thank you for clarifying.
the commits are separated right now for readability and can be squashed on merge.

**Comment by t-b** [comment]
@ukos-git 

This is just FYI:
See cf78ffa
- I've fixed the layout for multiple timeseries
- and reorganized a bit

**Pull request closed without merging**
